export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const MINE_TYPE = {
  OPEN_CAST: 'OPEN_CAST',
  UNDERGROUND: 'UNDERGROUND',
  MIXED: 'MIXED',
};

export const PAGE_TYPE = {
  PAGE: 'PAGE',
  MENU: 'MENU',
  GROUP: 'GROUP',
};

export const AUDIT_ACTION = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REVOKE: 'REVOKE',
  ASSIGN: 'ASSIGN',
  UNASSIGN: 'UNASSIGN',
};

export const ENTITY_TYPE = {
  ORGANIZATION: 'ORGANIZATION',
  MINE: 'MINE',
  USER: 'USER',
  ROLE: 'ROLE',
  SUBROLE: 'SUBROLE',
  PERMISSION: 'PERMISSION',
  ROLE_PERMISSION: 'ROLE_PERMISSION',
  SUBROLE_PERMISSION: 'SUBROLE_PERMISSION',
  USER_SUBROLE: 'USER_SUBROLE',
  PAGE: 'PAGE',
  PAGE_PERMISSION: 'PAGE_PERMISSION',
  USER_SESSION: 'USER_SESSION',
};
